permalink: pretty
highlighter: pygments
exclude: [ README.md, CONTRIBUTING.md, CNAME, Gemfile, Gemfile.lock, scripts/ ]
paginate: 10
paginate_path: "/news/:num"

site:
  title: Photos of Blacklion
  url: http://photosofblacklion.net

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
      category: "news"
  -
    scope:
      path: ""
      type: "albums"
    values:
      layout: "gallery"
      category: "album"

collections:
  albums:
    output: true
